# Generated by Django 5.1.7 on 2025-03-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='userprofile/')),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('pincode', models.CharField(max_length=6)),
                ('activation_code', models.CharField(blank=True, default='000000', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
