# Generated by Django 5.1.7 on 2025-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
